title: gunsch.cc
email: andrew@gunsch.cc
description: >- # this means to ignore newlines until "baseurl:"
  the personal website of andrew gunsch
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://gunsch.cc" # the base hostname & protocol for your site, e.g. http://example.com
github_username: gunsch

# Build settings
plugins:
  - jekyll-compress-images
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
exclude:
  - _compress_images_cache.yml

