version: 2.1
workflows:
  build:
    jobs:
      - build:
          context:
            - Everything
jobs:
  build:
    docker:
    - image: cimg/ruby:3.2.2
    steps:
      - checkout

      # Do Ruby-based setup
      - restore_cache:
          keys:
            - rubygems-v1-{{ checksum "Gemfile.lock" }}
            - rubygems-v1-fallback
      - run:
          name: Bundle Install
          command: bundle check || bundle install
      - save_cache:
          key: rubygems-v1-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      # Do the actual build!
      - run:
          name: Jekyll build
          command: bundle exec jekyll build

      # Create the Docker image
      - run:
          name: Docker build
          command: docker build --pull --rm -f "Dockerfile" -t gunsch.cc:latest "."

      # Use GitHub PAT to auth to GitHub Packages, then tag and push!
      - run: |
         echo "$GITHUB_TOKEN" | docker login https://docker.pkg.github.com --username gunsch --password-stdin
         TAG=0.1.$CIRCLE_BUILD_NUM
         docker tag gunsch.cc:latest docker.pkg.github.com/gunsch/gunsch.cc/gunschcc-$CIRCLE_BRANCH:$TAG
         docker push docker.pkg.github.com/gunsch/gunsch.cc/gunschcc-$CIRCLE_BRANCH:$TAG
