version: 2.1
workflows:
  build:
    jobs:
      - build:
          context:
            - Everything
orbs:
  ruby: circleci/ruby@2.1.0
jobs:
  build:
    machine:
      image: ubuntu-2004:202111-02
    steps:
      - checkout

      # Do Ruby-based setup
      - ruby/install:
          version: '3.2.2'
      - ruby/install-deps

      # Do the actual build!
      - run:
          name: Jekyll build
          command: bundle exec jekyll build

      # Create the Docker image
      - run:
          name: Docker build
          command: docker build --pull --rm -f "Dockerfile" -t gunsch.cc:latest "."

      # Use GitHub PAT to auth to GitHub Packages, then tag and push!
      - run: |
         echo "$GITHUB_TOKEN" | docker login https://docker.pkg.github.com --username gunsch --password-stdin
         TAG=0.1.$CIRCLE_BUILD_NUM
         docker tag gunsch.cc:latest docker.pkg.github.com/gunsch/gunsch.cc/gunschcc-$CIRCLE_BRANCH:$TAG
         docker push docker.pkg.github.com/gunsch/gunsch.cc/gunschcc-$CIRCLE_BRANCH:$TAG
