version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs:
 build:
   machine: true
   steps:
     - checkout

     # Install latest node and verify the version
     - node/install:
         node-version: latest
     - run: node --version

     # Install packages (`npm ci` under the hood)
     - node/install-packages

     # Do the actual build!
     - run: ./build.sh

     # Use GitHub PAT to auth to GitHub Packages, then tag and push!
     - run: |
         echo "$GITHUB_TOKEN" | docker login https://docker.pkg.github.com --username gunsch --password-stdin
         TAG=0.1.$CIRCLE_BUILD_NUM
         docker tag gunsch.cc:latest docker.pkg.github.com/gunsch/gunsch.cc/$CIRCLE_BRANCH:$TAG
         docker push docker.pkg.github.com/gunsch/gunsch.cc/$CIRCLE_BRANCH:$TAG
